/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubespbo;

import java.awt.Color;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Sefruit Cerita
 */
public class KalkulatorBMI extends javax.swing.JFrame {
    private int x;
    private int y;
    /**
     * Creates new form KalkulatorBMI
     */
    public KalkulatorBMI() {
        initComponents();
        this.setLocationRelativeTo(null); // center form in the screen
        this.setResizable(false); // prevent frame from being resized
        ImageIcon logo = new ImageIcon("src/image/logoframe.png"); // create image icon
        this.setIconImage(logo.getImage()); // change icon of frame
        hitungButton.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        bmiFrame = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        matangButton = new javax.swing.JButton();
        bilanganButton = new javax.swing.JButton();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        usiaTextField = new javax.swing.JTextField();
        beratTextField = new javax.swing.JTextField();
        tinggiTextField = new javax.swing.JTextField();
        wanitaButton = new keeptoo.KGradientPanel();
        jLabel11 = new javax.swing.JLabel();
        wanitaRadioButton = new javax.swing.JRadioButton();
        priaButton = new keeptoo.KGradientPanel();
        jLabel10 = new javax.swing.JLabel();
        priaRadioButton = new javax.swing.JRadioButton();
        hitungButton = new javax.swing.JButton();
        restartButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkuleta | Kalkulator BMI");
        setUndecorated(true);

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 102, 51));
        kGradientPanel1.setkGradientFocus(700);
        kGradientPanel1.setkStartColor(new java.awt.Color(153, 255, 153));

        bmiFrame.setBackground(new java.awt.Color(0, 0, 0));
        bmiFrame.setPreferredSize(new java.awt.Dimension(90, 36));
        bmiFrame.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bmiFrameMouseDragged(evt);
            }
        });
        bmiFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bmiFrameMousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cross-square-button (2) (1).png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/minimize (5) (1).png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 204));
        jLabel3.setText("Kalkulator BMI");

        javax.swing.GroupLayout bmiFrameLayout = new javax.swing.GroupLayout(bmiFrame);
        bmiFrame.setLayout(bmiFrameLayout);
        bmiFrameLayout.setHorizontalGroup(
            bmiFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bmiFrameLayout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bmiFrameLayout.setVerticalGroup(
            bmiFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bmiFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(10, 10, 10))
        );

        jPanel3.setBackground(new java.awt.Color(102, 51, 0));

        matangButton.setBackground(new java.awt.Color(189, 112, 9));
        matangButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        matangButton.setText("Konversi Mata Uang");
        matangButton.setFocusable(false);
        matangButton.setPreferredSize(new java.awt.Dimension(207, 31));
        matangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matangButtonActionPerformed(evt);
            }
        });

        bilanganButton.setBackground(new java.awt.Color(189, 112, 9));
        bilanganButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        bilanganButton.setText("Kalkulator Bilangan");
        bilanganButton.setFocusable(false);
        bilanganButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bilanganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilanganButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(bilanganButton, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(matangButton, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bilanganButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matangButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        kGradientPanel3.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel3.setkStartColor(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Gender");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setText("Berat");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Usia ");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setText("Tinggi");

        usiaTextField.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        usiaTextField.setForeground(new java.awt.Color(102, 102, 102));
        usiaTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usiaTextField.setText("Th");
        usiaTextField.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        usiaTextField.setPreferredSize(new java.awt.Dimension(75, 23));
        usiaTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usiaTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usiaTextFieldFocusLost(evt);
            }
        });

        beratTextField.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        beratTextField.setForeground(new java.awt.Color(102, 102, 102));
        beratTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        beratTextField.setText("Kg");
        beratTextField.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        beratTextField.setPreferredSize(new java.awt.Dimension(75, 23));
        beratTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                beratTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                beratTextFieldFocusLost(evt);
            }
        });

        tinggiTextField.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tinggiTextField.setForeground(new java.awt.Color(102, 102, 102));
        tinggiTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tinggiTextField.setText("Cm");
        tinggiTextField.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        tinggiTextField.setPreferredSize(new java.awt.Dimension(75, 23));
        tinggiTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tinggiTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tinggiTextFieldFocusLost(evt);
            }
        });

        wanitaButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        wanitaButton.setkEndColor(new java.awt.Color(249, 211, 154));
        wanitaButton.setkStartColor(new java.awt.Color(249, 211, 154));
        wanitaButton.setPreferredSize(new java.awt.Dimension(75, 23));
        wanitaButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                wanitaButtonMouseMoved(evt);
            }
        });
        wanitaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wanitaButtonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                wanitaButtonMouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel11.setText("Wanita");

        wanitaRadioButton.setBackground(new java.awt.Color(249, 211, 154));
        genderButtonGroup.add(wanitaRadioButton);
        wanitaRadioButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profile (2).png"))); // NOI18N

        javax.swing.GroupLayout wanitaButtonLayout = new javax.swing.GroupLayout(wanitaButton);
        wanitaButton.setLayout(wanitaButtonLayout);
        wanitaButtonLayout.setHorizontalGroup(
            wanitaButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wanitaButtonLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(wanitaButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(wanitaRadioButton)
                    .addComponent(jLabel11))
                .addGap(19, 19, 19))
        );
        wanitaButtonLayout.setVerticalGroup(
            wanitaButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wanitaButtonLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(wanitaRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        priaButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        priaButton.setkEndColor(new java.awt.Color(249, 211, 154));
        priaButton.setkStartColor(new java.awt.Color(249, 211, 154));
        priaButton.setPreferredSize(new java.awt.Dimension(75, 23));
        priaButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                priaButtonMouseMoved(evt);
            }
        });
        priaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                priaButtonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                priaButtonMouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel10.setText("Pria");

        priaRadioButton.setBackground(new java.awt.Color(249, 211, 154));
        genderButtonGroup.add(priaRadioButton);
        priaRadioButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profile (1).png"))); // NOI18N

        javax.swing.GroupLayout priaButtonLayout = new javax.swing.GroupLayout(priaButton);
        priaButton.setLayout(priaButtonLayout);
        priaButtonLayout.setHorizontalGroup(
            priaButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(priaButtonLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(priaRadioButton)
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, priaButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(25, 25, 25))
        );
        priaButtonLayout.setVerticalGroup(
            priaButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(priaButtonLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(priaRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(12, 12, 12))
        );

        hitungButton.setBackground(new java.awt.Color(153, 255, 153));
        hitungButton.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        hitungButton.setText("Hitung");
        hitungButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(56, 56, 56)
                .addComponent(jLabel5)
                .addGap(51, 51, 51)
                .addComponent(jLabel7)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel3Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel3Layout.createSequentialGroup()
                        .addComponent(hitungButton, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel3Layout.createSequentialGroup()
                        .addComponent(priaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wanitaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(usiaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(beratTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(tinggiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wanitaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(usiaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(beratTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tinggiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addComponent(hitungButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        restartButton.setBackground(new java.awt.Color(255, 255, 255));
        restartButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        restartButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reuse (1) (3).png"))); // NOI18N
        restartButton.setFocusable(false);
        restartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartButtonActionPerformed(evt);
            }
        });

        homeButton.setBackground(new java.awt.Color(153, 153, 153));
        homeButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home (1) (2).png"))); // NOI18N
        homeButton.setFocusable(false);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setPreferredSize(new java.awt.Dimension(444, 8));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setPreferredSize(new java.awt.Dimension(444, 8));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 219, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(102, 51, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(102, 51, 0));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(102, 51, 0));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bmiFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(kGradientPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kGradientPanel1Layout.createSequentialGroup()
                        .addGap(440, 440, 440)
                        .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(restartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                    .addGap(120, 120, 120)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(458, Short.MAX_VALUE)))
            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                    .addGap(92, 92, 92)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(465, Short.MAX_VALUE)))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addComponent(bmiFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kGradientPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(restartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                    .addContainerGap(524, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(62, 62, 62)))
            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                    .addContainerGap(525, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(62, 62, 62)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setExtendedState(KalkulatorBMI.ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void bmiFrameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bmiFrameMousePressed
        this.x = evt.getX();
        this.y = evt.getY();
    }//GEN-LAST:event_bmiFrameMousePressed

    private void bmiFrameMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bmiFrameMouseDragged
        int x1 = evt.getXOnScreen();
        int y1 = evt.getYOnScreen();
        
        this.setLocation(x1-x, y1-y);
    }//GEN-LAST:event_bmiFrameMouseDragged

    private void matangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matangButtonActionPerformed
        KonversiMataUang konversiMataUang = new KonversiMataUang();
        konversiMataUang.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_matangButtonActionPerformed

    private void bilanganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilanganButtonActionPerformed
        KonversiBilangan konversiBilangan = new KonversiBilangan();
        konversiBilangan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bilanganButtonActionPerformed

    private void hitungButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungButtonActionPerformed
        double hitung = Double.parseDouble(beratTextField.getText())/(Double.parseDouble(tinggiTextField.getText())*Double.parseDouble(tinggiTextField.getText())/10000);
        HasilAkhirBMI hasil = new HasilAkhirBMI();
        DecimalFormat koma = new DecimalFormat("#.##");
        hasil.bmiTextField.setText(koma.format(hitung));

        if (priaRadioButton.isSelected()){
            if(hitung<=18.00){
                hasil.bbTextField.setText("Kurus");
            }
            else if(hitung>=18.00 && hitung<=24.99){
                hasil.bbTextField.setText("Normal");
            }
            else if(hitung>=25.00 && hitung<=26.99){
                hasil.bbTextField.setText("Kegemukan");
            }
            else if(hitung>=27.00){
                hasil.bbTextField.setText("Obesitas");
            }
            else {
                hasil.bbTextField.setText("Invalid");
            }
        }else{
            if(hitung<=17.00){
                hasil.bbTextField.setText("Kurus");
            }
            else if(hitung>=17.00 && hitung<=22.99){
                hasil.bbTextField.setText("Normal");
            }
            else if(hitung>=23.00 && hitung<=26.99){
                hasil.bbTextField.setText("Kegemukan");
            }
            else if(hitung>=27.00){
                hasil.bbTextField.setText("Obesitas");
            }
            else {
                hasil.bbTextField.setText("Invalid");
            }         
        }
        
        hasil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_hitungButtonActionPerformed

    private void usiaTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usiaTextFieldFocusGained
        if(usiaTextField.getText().equals("Th")){
            usiaTextField.setText("");
            usiaTextField.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_usiaTextFieldFocusGained

    private void usiaTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usiaTextFieldFocusLost
        if(usiaTextField.getText().equals("")){
            usiaTextField.setText("Th");
            usiaTextField.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_usiaTextFieldFocusLost

    private void beratTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_beratTextFieldFocusGained
        if(beratTextField.getText().equals("Kg")){
            beratTextField.setText("");
            beratTextField.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_beratTextFieldFocusGained

    private void beratTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_beratTextFieldFocusLost
        if(beratTextField.getText().equals("")){
            beratTextField.setText("Kg");
            beratTextField.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_beratTextFieldFocusLost

    private void tinggiTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tinggiTextFieldFocusGained
        if(tinggiTextField.getText().equals("Cm")){
            tinggiTextField.setText("");
            tinggiTextField.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_tinggiTextFieldFocusGained

    private void tinggiTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tinggiTextFieldFocusLost
        if(tinggiTextField.getText().equals("")){
            tinggiTextField.setText("Cm");
            tinggiTextField.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_tinggiTextFieldFocusLost

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        Rumah home = new Rumah();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void restartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartButtonActionPerformed
        usiaTextField.setText("Th");
        usiaTextField.setForeground(new Color(102,102,102));
        beratTextField.setText("Kg");
        beratTextField.setForeground(new Color(102,102,102));
        tinggiTextField.setText("Cm");
        tinggiTextField.setForeground(new Color(102,102,102));
        hitungButton.requestFocus();
    }//GEN-LAST:event_restartButtonActionPerformed

    private void priaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_priaButtonMouseClicked
        priaButton.requestFocus();
    }//GEN-LAST:event_priaButtonMouseClicked

    private void wanitaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wanitaButtonMouseClicked
        wanitaButton.requestFocus();
    }//GEN-LAST:event_wanitaButtonMouseClicked

    private void priaButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_priaButtonMouseMoved
        priaButton.setBackground(Colors.INSTANCE.mouseMovedColor());
    }//GEN-LAST:event_priaButtonMouseMoved

    private void priaButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_priaButtonMouseExited
        priaButton.setBackground(Colors.INSTANCE.secondaryColor());
    }//GEN-LAST:event_priaButtonMouseExited

    private void wanitaButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wanitaButtonMouseMoved
        wanitaButton.setBackground(Colors.INSTANCE.mouseMovedColor());
    }//GEN-LAST:event_wanitaButtonMouseMoved

    private void wanitaButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wanitaButtonMouseExited
        wanitaButton.setBackground(Colors.INSTANCE.secondaryColor());
    }//GEN-LAST:event_wanitaButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KalkulatorBMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KalkulatorBMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KalkulatorBMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KalkulatorBMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KalkulatorBMI().setVisible(true);
            }
        });
    }
    
    public void setColors(){
        priaButton.setBackground(Colors.INSTANCE.secondaryColor());
        wanitaButton.setBackground(Colors.INSTANCE.secondaryColor());   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField beratTextField;
    private javax.swing.JButton bilanganButton;
    private javax.swing.JPanel bmiFrame;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JButton hitungButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel3;
    private javax.swing.JButton matangButton;
    private keeptoo.KGradientPanel priaButton;
    private javax.swing.JRadioButton priaRadioButton;
    private javax.swing.JButton restartButton;
    public static javax.swing.JTextField tinggiTextField;
    public javax.swing.JTextField usiaTextField;
    private keeptoo.KGradientPanel wanitaButton;
    private javax.swing.JRadioButton wanitaRadioButton;
    // End of variables declaration//GEN-END:variables
}
